### ISSUE TITLE
Eliom and OCaml 4.03.0

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#313] opened 2016-06-15 09:06 UTC
Many things seem to be broken with OCaml 4.03. I don't really understand te problem yet.
It seems to involve react signal in client side code.
An exemple of minimal broken program is the following:
```ocaml
[%%client
let _ =
  let s, set = React.S.create 4 in
  ignore
    (React.S.map
       (fun pos ->
          print_endline "aaaa";
       ) s);
  set 65;
  set 76;
  let elt = Eliom_content.Html.D.p [pcdata "CLICK"] in
  Eliom_content.Html.Manip.appendToBody elt;
  Lwt.async (fun () ->
    Lwt_js_events.clicks (Eliom_content.Html.To_dom.of_element elt) (fun _ _ ->
      print_endline "clic";
      set 66;
      Lwt.return ()
    ))
]
```
Clicking on th element displays "clic" but not "aaaa".

(To compile Eliom with OCaml 4.03.0 you need dev version of ocamlnet).

**Comment by vasilisp** [comment] 2016-06-15 11:34
I am not sure that this is the source of your trouble. I get "aaaa" on the first click, but not on the subsequent clicks. This is normal, because the signal stays 66 afterwards, and the downstream signals are not supposed to change.

**Comment by balat** [comment] 2016-06-15 12:22
Yes sorry I simplified too much ;)
The correct example is this one:

```ocaml
let s = [%client (React.S.create 4 : _ * _) ]

[%%client
let _ =
  let%lwt () = Lwt_js.sleep 3. in
  let s, set = ~%s in
  ignore
    (React.S.map
       (fun pos ->
          print_endline "aaaa";
       ) s);
  set 65;
  set 76;
  let elt = Eliom_content.Html.D.p [pcdata "CLICK"] in
  Eliom_content.Html.Manip.appendToBody elt;
  Lwt.async (fun () ->
    Lwt_js_events.clicks (Eliom_content.Html.To_dom.of_element elt) (fun _ _ ->
      print_endline "clic";
      set (Random.int 66);
      Lwt.return ()
    ));
  Lwt.return ()
]
```

**Comment by balat** [comment] 2016-06-15 12:39
(at least I guess).
The initial example I'm trying to reduce is Ot_carousel.ribbon.
It has very weird behaviours related to React.S.map (or here React.S.l3) on injected signals.
Sometimes it works, other times not ...
The ribbon is completely broken.

I don't know if the culprit is ocaml 4.03 or some change in other recent packages (js_of_ocaml ?)

**Comment by vasilisp** [comment] 2016-06-15 12:42
Your second example is broken with 4.02.3 as well. You can fix it by providing the type of `s`:

```ocaml
let s = [%client
  (React.S.create 4 : (int React.S.t * (?step:React.step -> int -> unit)))
]
```

That looks like a bug with the typing of injections (albeit not 4.03-specific), the user-provided annotation shouldn't be "shadowing" a fully-known type.

**Comment by balat** [comment] 2016-06-15 12:44
Indeed, it is also broken with 4.02.3.
Thanks for the workaround.
However, the ribbon is not broken with 4.02 ...

**Comment by vasilisp** [comment] 2016-06-15 12:56
It may be that we have the bad habit of ignoring the typing warnings, and there was always trouble waiting to appear :).  `Ot_carousel` has lots of injections, so maybe we can try adding some more precise type annotations to narrow down the problem.

At second glance, I doubt we can do much for the type inference issue above (with the current Eliom, anyway).

**Comment by balat** [comment] 2016-06-15 12:58
I added all the warnings in Ot_carousel by adding type annotations.
But it does not solve the problem :/
Still experimenting ..

**Comment by balat** [comment] 2016-06-15 14:28
I'm giving up for now. The problem with 4.03 seems much worse than expected.
I have been unable to reproduce it on a small example.
Did you manage to reproduce it with ot_ribbon? (I think there is an example of use in eba_template (?)).

**Comment by vasilisp** [comment] 2016-06-15 14:38
Yes, I can reproduce it as follows:

```ocaml
let s, f = Eliom_shared.React.S.create 0

let () =
  I313_app.register
    ~service:main_service
    (fun () () ->
       let e =
         Eliom_tools.F.html
           ~title:"i313"
           ~css:[["css";"i313.css"]]
           Html.F.(body [
	     h1 [pcdata "Welcome from Eliom's distillery!"];
             Ot_carousel.ribbon
               ~change:[%client
                 ((fun _ -> ()) :                                               
                    ([ `Goto of int | `Next | `Prev ] -> unit))]
               ~pos:s
               [[pcdata "foo"];
                [pcdata "bar"]];
             p ~a:[a_onclick [%client (fun _ -> ~%f 1)]] [pcdata "set 1"];
           ])
       in
       Lwt.return e)
```

After I press the button to set `s`, none of the elements has the`active` class. I don't know what is going on yet, but working on it.

**Comment by vasilisp** [comment] 2016-06-15 16:12
When I isolate the code that reactively sets/unsets the `"active"` class, everything works fine, but when this code is in the context of other reactive things, things break down. To me this looks like JSOO + `React` trouble. I produced the following failing example:

```ocaml
open Lwt.Infix

let pos, set_pos = React.S.create 0

let print i (pos : int React.S.t) =
  React.S.map (fun pos -> Printf.printf "%d [%d]\n%!" i pos) pos

let l = [print 0 pos; print 1 pos]

(* comment this out and you see the expected messages *)
let _ = React.S.map (fun _ -> ()) pos

let _ =
  Lwt.async @@ fun () ->
  Lwt_js_events.onload () >>= fun _ ->
  let open Tyxml_js in
  Register.body
    [Html.(p ~a:[a_onclick (fun _ -> set_pos 1; true)] [pcdata "set 1"])];
  Lwt.return ()
```

The presence of `let _ = React.S.map (fun _ -> ()) pos` means that some of the other reactive updates don't happen.

**Comment by balat** [comment] 2016-06-15 16:56
Ok at least your example does not contain injections.

What are the new features of 4.03 that could interfere with jsoo or react?
Weak pointers and ephemerons may be?

**Comment by vouillon** [comment] 2016-06-15 18:37
Indeed, this might be a bug in the implementation of ephemerons in jsoo.

**Comment by vasilisp** [comment] 2016-06-15 21:18
While ephemerons and weak references are very related, all that JSOO does for ephemerons is provide some primitives (ocsigen/js_of_ocaml@abf7e122d9de3dfb8fc2f14bbc69f9cbe7b5666f). I don't think these are used for anything else.

But 4.03 did necessitate changes for `Weak` (ocsigen/js_of_ocaml@1cd9deb706a339b314f5746daaba0c13c56f903b), so that might be the culprit.

**Comment by vasilisp** [comment] 2016-06-15 21:44
If I revert ocsigen/js_of_ocaml@1cd9deb, the small non-Eliom example seems to work.

The program uses these four primitives: `caml_weak_blit`, `caml_weak_create`,  `caml_weak_get`, and `caml_weak_set`, and ocsigen/js_of_ocaml@1cd9deb touches all but `caml_weak_blit`, so maybe that one also has to take the different offsets into account?

**Comment by vasilisp** [comment] 2016-06-15 22:08
I made a very speculative patch for `caml_weak_blit` (ocsigen/js_of_ocaml@4b1fbe627ff64239eef84531430e3ddf7425b6f0), and it seems to fix the issue. @hhugo, does this look reasonable?

**Comment by hhugo** [comment] 2016-06-16 08:12
Thanks for investigating. I've try to clean & fix weak.js. Can you try with https://github.com/ocsigen/js_of_ocaml/commit/8d0b817a10136406c620eaa72dc054f4de364d8d

**Comment by vasilisp** [comment] 2016-06-16 10:33
@hhugo, I saw your latest commit, and the [plain JSOO example](#issuecomment-226238196) is still broken, unfortunately. While the original version (`= caml_array_blit`) seems to be off-by-one even for 4.02, that off-by-one somehow makes `React` work...

**Comment by hhugo** [comment] 2016-06-16 11:08
There was indeed a typo in `blit` - now fixed - your speculative patch was just right

**Comment by balat** [comment] 2016-06-16 14:38
It works for me with the last js_of_ocaml !
Many thanks to both of you :)

**Closed** 2016-06-16 14:38 UTC
